project:
  output-dir: ./docs/

lang: en

website:
  navbar:
    title: "Home"
    right:
      - icon: github
        href: https://github.com/neurodevco
        aria-label: GitHub
      - icon: twitter
        href: https://github.com/neurodevco
        aria-label: Twitter
      - href: ./
        text: English
      - href: ./ca/
        text: Català
      - href: ./es/
        text: Español
    left:
      - href: pages/people.qmd
        text: People
      - text: Research
        menu:
          - text: Studies with babies
            href: pages/babies.qmd
          - text: Animal research
            href: pages/animals.qmd
      - href: pages/contact.qmd
        text: Contact
