project:
  type: website

website:
  title: "NeuroDevComp"
  favicon: static/img/favicon.ico
  navbar:
    title: "NeuroDevComp"
    logo: static/img/ndc-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - text: Research
        menu:
          - text: Studies with babies
            href: babies.qmd
          - text: Animal research
            href: animals.qmd
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/NeuroDevComp
        aria-label: GitHub
      - icon: twitter
        href: https://github.com/NeuroDevComp
        aria-label: Twitter
    search: true
  twitter-card: true
  site-url: https://neurodevcomp.github.io
  open-graph: true
  page-footer: 
    left: "![](static/img/erc.png){height='80px' style='vertical-align: middle;'}"
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
    center: |
      {{< fa location-dot >}}  C. de Sta. Rosa, 39 | 08950 Barcelona

      {{< fa phone >}} XXXX-XXXX-XXXX

      {{< fa envelope >}} [neurodevcomp@sjd.es](mailto:neurodevcomp@sjd.es)

      <br>

    background: "#f1f1f1"
  

format:
  html:
    theme: cosmo
    css: static/styles/styles.css
    toc: true
    smooth-scroll: true
    body-width: 1000px
    linkcolor: black
    grid: 
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 200px
