project:
  type: website
  output-dir: docs
  resources: 
    - static/fonts/
    - static/img/background.svg


website:
  navbar: true

format:
  html:
    theme: cosmo
    css:
      - static/styles/styles.css
      - static/styles/styles.scss
    toc: true
    smooth-scroll: true
    body-width: 1000px
    linkcolor: black
    grid: 
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 200px
    email-obfuscation: javascript
    include-before-body: static/templates/background.html
    
babelquarto:
  mainlanguage: 'en'
  languages: ['ca', 'es']
