project:
  output-dir: ./docs/en

lang: en

website:
  navbar:
    title: "NeuroDevComp"
    right:
      - icon: github
        href: https://github.com/NeuroDevComp
        aria-label: GitHub
      - icon: twitter
        href: https://github.com/NeuroDevComp
        aria-label: Twitter
    left:
      - href: people.qmd
        text: People
      - text: Research
        menu:
          - text: Studies with babies
            href: babies.qmd
          - text: Animal research
            href: animals.qmd
      - href: contact.qmd
        text: Contact
