project:
  type: website
  output-dir: docs
  resources:
    - static/fonts/
    - static/img/background.svg


website:
  navbar: true
  site-url: https://neurodevco.github.io

format:
  html:
    theme: cosmo
    css:
      - static/styles/styles.css
    toc: true
    smooth-scroll: true
    body-width: 1000px
    linkcolor: black
    grid:
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 200px
    email-obfuscation: javascript
    include-before-body: static/templates/background.html

babelquarto:
#   icon: "bi bi-backpack"
#   languagecodes:
#     - names: en
#       text: English
#     - name: ca
#       text: Català
#     - name: es
#       text: Español
  mainlanguage: 'en'
  languages: ['ca', 'es']
lang: en
