project:
  output-dir: ./docs/es

lang: es

website:
  navbar:
    right:
      - icon: github
        href: https://github.com/neurodevco
        aria-label: GitHub
      - icon: twitter
        href: https://github.com/neurodevco
        aria-label: Twitter
      - href: ../
        text: English
      - href: ../ca/
        text: Català
      - href: ../es/
        text: Español
    left:
      - href: people.qmd
        text: ¿Quiénes somos?
      - text: Investigación
        menu:
          - text: Estudios con bebés
            href: babies.qmd
          - text: Estudios con animales
            href: animals.qmd
      - href: contact.qmd
        text: Contacto
