project:
  output-dir: ./docs/

lang: en

website:
  navbar:
    title: "NeuroDevComp"
    right:
      - icon: github
        href: https://github.com/neurodevco
        aria-label: GitHub
      - icon: twitter
        href: https://github.com/neurodevco
        aria-label: Twitter
      - href: ./
        text: English
      - href: ./ca/
        text: Català
      - href: ./es/
        text: Español
    left:
      - href: people.qmd
        text: People
      - text: Research
        menu:
          - text: Studies with babies
            href: babies.qmd
          - text: Animal research
            href: animals.qmd
      - href: contact.qmd
        text: Contact
