on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      # install libcurl, needed for curl R package
      - name: Install R package deps
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libpng-dev libjpeg-turbo8-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.3"

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            github::ropensci-review-tools/babelquarto@a485fea
      - name: Render Book with babelquarto
        run: Rscript -e 'babelquarto::render_book()'
      - name: Achive book render
        uses: actions/upload-artifact@v4
        with:
          name: book_render
          path: docs/

      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
